covidance/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using covidance.Data;
using Microsoft.Extensions.Logging;
using covidance.Lib.Communications;

namespace covidance.Controllers
{
    
    public class PersonsController : BaseAuthenticatedController
    {
        private readonly CovidanceContext _context;
        private IQueryable<PersonInfo> _defaultPersons;
        private readonly IMyEmailSender _emailSender;
        private readonly ILogger<PersonsController> _logger;

        public PersonsController(CovidanceContext context, ILogger<PersonsController> logger, IMyEmailSender emailSender)
        {
            _context = context;
            _defaultPersons = _context.Persons.Where(x => x.UserId == User.Identity.Name);
            _logger = logger;
            _emailSender = emailSender;
        }

        // GET: Persons
        public async Task<IActionResult> Index()
        {
            return View(await _defaultPersons.ToListAsync());
        }

        // GET: Persons/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInfo = await _defaultPersons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personInfo == null)
            {
                return NotFound();
            }

            return View(personInfo);
        }

        // GET: Persons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Email")] PersonInfo personInfo)
        {
            if (ModelState.IsValid)
            {
                personInfo.Id = Guid.NewGuid();
                personInfo.UserId = User.Identity.Name;
                _context.Add(personInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personInfo);
        }

        // GET: Persons/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInfo = await _defaultPersons.SingleOrDefaultAsync(x => x.Id == id);
            if (personInfo == null)
            {
                return NotFound();
            }
            return View(personInfo);
        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name,Email,Deleted")] PersonInfo personInfo)
        {
            if (id != personInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonInfoExists(personInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(personInfo);
        }

        // GET: Persons/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personInfo = await _defaultPersons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personInfo == null)
            {
                return NotFound();
            }

            return View(personInfo);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var personInfo = await _defaultPersons.SingleOrDefaultAsync(x => x.Id == id);
            _context.Persons.Remove(personInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonInfoExists(Guid id)
        {
            return _defaultPersons.Any(e => e.Id == id);
        }
    }
}

covidance/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using covidance.Data;
using covidance.Lib.Communications;
using Microsoft.Extensions.Logging;

namespace covidance.Controllers
{
    public class RecordsController : BaseAuthenticatedController
    {
        private readonly CovidanceContext _context;
        private IQueryable<RecordInfo> _defaultRecords;
        private readonly IMyEmailSender _emailSender;
        private readonly ILogger<RecordsController> _logger;
        public RecordsController(CovidanceContext context, ILogger<RecordsController> logger, IMyEmailSender emailSender)
        {
            _context = context;
            _defaultRecords = _context.Records.Where(x => x.PersonInfo.UserId == User.Identity.Name);
            _logger = logger;
            _emailSender = emailSender;
        }

        // GET: Records
        public async Task<IActionResult> History()
        {
            DateTime now = DateTime.UtcNow.AddDays(-14);
            return View(await _defaultRecords.Where(x => x.When >= now).ToListAsync());
        }

        public async Task<IActionResult> Index()
        {
            DateTime now = DateTime.UtcNow;
            var allPeeps = _context.Persons.Where(x => x.UserId == User.Identity.Name);
            var scannedBeforeNow = _context.Records
                                            .Where(x => x.PersonInfo.UserId == User.Identity.Name)
                                            .Where(x => x.When < now)
                                            .Select(x => x.PersonInfoId)
                                            .Distinct();
            var toscan = allPeeps.Where(x => !scannedBeforeNow.Contains(x.Id));
            return View(await toscan.ToListAsync());
        }

        // GET: Records/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recordInfo = await _defaultRecords
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recordInfo == null)
            {
                return NotFound();
            }

            return View(recordInfo);
        }

        // GET: Records/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Records/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("When,Temperature,Symptoms,RecentContact,Sanitised,Bagged,Reason")] RecordInfo recordInfo)
        {
            if (ModelState.IsValid)
            {
                recordInfo.Id = Guid.NewGuid();
                recordInfo.DateCreated = DateTime.UtcNow;
                _context.Add(recordInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recordInfo);
        }

        // GET: Records/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recordInfo = await _defaultRecords
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recordInfo == null)
            {
                return NotFound();
            }

            return View(recordInfo);
        }

        // POST: Records/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var recordInfo = await _defaultRecords.SingleOrDefaultAsync(x => x.Id == id);
            _context.Records.Remove(recordInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecordInfoExists(Guid id)
        {
            return _defaultRecords.Any(e => e.Id == id);
        }
    }
}

covidance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - covidance</title>
    <link rel="stylesheet" href="~/css/fontawesome.css" />
    <link rel="stylesheet" href="~/css/tailwind.min.css" />
    <link rel="stylesheet" href="~/css/emoji.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-gray-900 font-sans leading-normal tracking-normal mt-12">

    <nav class="bg-gray-900 pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">
        <div class="flex flex-wrap items-center">
            <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
                <a href="/">
                    <span class="text-xl pl-2"><i class="em em-grinning"></i></span>
                </a>
            </div>
        </div>

        <partial name="_LoginPartial" />
        <partial name="_LoggedInPartial" />

    </nav>
    
    <div class="flex flex-col md:flex-row">

        <partial name="_LoggedinNav" />

        <div class="main-content flex-1 bg-grey-lightest mt-12 md:mt-2 pb-24 md:pb-5">
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container inline-block py-2 px-4 text-white no-underline">
            &copy; 2020 - covidance - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="inline-block py-2 px-4 text-white no-underline">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/Chart.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

covidance/Views/Shared/_LoggedInNav.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{

    <div class="bg-gray-900 shadow-lg h-16 fixed bottom-0 mt-12 md:relative md:h-screen z-10 w-full md:w-48">
        <div class="md:mt-12 md:w-48 md:fixed md:pin-l md:pin-t content-center md:content-start text-left justify-between">
            <ul class="list-reset flex flex-row md:flex-col py-0 md:py-3 px-1 md:px-2 text-center md:text-left">
                <li class="mr-3 flex-1">
                    <a asp-area="" asp-controller="Persons" asp-action="Index" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-grey-darkest hover:border-purple">
                        <i class="fa fa-users pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block">People</span>
                    </a>
                </li>
                <li class="mr-3 flex-1">
                    <a asp-area="" asp-controller="Records" asp-action="Index" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-grey-darkest hover:border-pink">
                        <i class="fas fa-tasks pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-grey-dark md:text-grey-light block md:inline-block">Scans</span>
                    </a>
                </li>
                <li class="mr-3 flex-1">
                    <a asp-area="" asp-controller="Records" asp-action="History" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-blue-dark">
                        <i class="fas fa-chart-area pr-0 md:pr-3 text-blue-dark"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:text-white block md:inline-block">History</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>

}

covidance/Views/Shared/_LoggedInPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{

    <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
        <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">
            <li class="flex-1 md:flex-none md:mr-3">
                <div class="relative inline-block">
                    <button onclick="toggleDD('myDropdown')" class="drop-button text-white focus:outline-none"> <span class="pr-2"><i class="em em-robot_face"></i></span> Hi, @User.Identity.Name <svg class="h-3 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /></svg></button>
                    <div id="myDropdown" class="dropdownlist absolute bg-black text-white pin-r mt-3 p-3 overflow-auto z-30 invisible">
                        <a asp-area="Identity" asp-page="/Account/Manage/Index" class="p-2 hover:bg-grey-darkest text-white text-sm no-underline hover:no-underline block"><i class="fa fa-user fa-fw"></i> Profile</a>
                        <div class="border border-grey-darkest"></div>
                        <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })" class="p-2 hover:bg-grey-darkest text-white text-sm no-underline hover:no-underline block"><i class="fas fa-sign-out-alt fa-fw"></i> Log Out</a>
                    </div>
                </div>
            </li>
        </ul>
    </div>


    <script>
        /*Toggle dropdown list*/
        function toggleDD(myDropMenu) {
            document.getElementById(myDropMenu).classList.toggle("invisible");
        }

        /*Filter dropdown options*/
        function filterDD(myDropMenu, myDropMenuSearch) {
            var input, filter, ul, li, a, i;
            input = document.getElementById(myDropMenuSearch);
            filter = input.value.toUpperCase();
            div = document.getElementById(myDropMenu);
            a = div.getElementsByTagName("a");
            for (i = 0; i < a.length; i++) {
                if (a[i].innerHTML.toUpperCase().indexOf(filter) > -1) {
                    a[i].style.display = "";
                } else {
                    a[i].style.display = "none";
                }
            }
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.drop-button') && !event.target.matches('.drop-search')) {

                var dropdowns = document.getElementsByClassName("dropdownlist");
                for (var i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (!openDropdown.classList.contains('invisible')) {
                        openDropdown.classList.add('invisible');
                    }
                }
            }
        }
    </script>

}